version: "1.0"

git:
  submodule: true
  timeout: 120

agent:
  docker:
    image: reg.docker.alibaba-inc.com/fma/tugraph-env-centos7.3:1.0.2

environments:
- CTEST_OUTPUT_ON_FAILURE: "1"

stages:
- TEST-AND-CODECOV

test-and-codecov:
  stage: TEST-AND-CODECOV
  steps:
    - plugin: clone
    - plugin: shell
      resources:
        cpu: 8
        mem: 16
        disk: 20
      inputs:
        image: reg.docker.alibaba-inc.com/fma/tugraph-env-centos7.3:1.0.2
        command:
        - |
          bash ./cpplint/check_all.sh
          mkdir -p build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Coverage
          make -j6
          cd output
          ./unit_test -t all
